# Generated by Django 4.2.4 on 2023-10-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_picture_alter_blog_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
